<refEntry>
 <refnamediv>
  <refname>User Guide for JFPersistentObject</refname>
  <refpurpose>To demonstrate the various tasks available in My app</refpurpose>
 </refnamediv>
 <refsynopsisdiv>
  <author>
   My Name
   <authorblurb>
    {@link mailto:myself@myhost.net My Name}
   </authorblurb>
  </author>
 </refsynopsisdiv>
 {@toc}
 <refsect1 id="{@id intro}">
  <title>Using JFPersistentObject</title>
<para>
This is <emphasis>important</emphasis>: never stick the tines of a fork
in an electrical outlet.
</para>

 </refsect1>

</refEntry>